### ISSUE TITLE
morning session peer to peer code review

### ISSUE THREAD

**Issue by JakariaJishan** [anderCM/bootstrap-portfolio#2]
The recommendations are:
- Kindly add a description in the alt part for every image
- Kindly consider using a list for the elements on your nav var
other than these issues, all the things are good, you did a good job.

**Comment by anderCM** [comment]
Issue fixed in this  [PR](https://github.com/anderCM/bootstrap-portfolio/pull/3)

**Comment by anderCM** [comment]
Issue fixed in this  [PR](https://github.com/anderCM/bootstrap-portfolio/pull/3)
